# Generated by Django 2.2.4 on 2019-11-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0002_auto_20191103_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='concentrate',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
