# Generated by Django 2.2.4 on 2019-11-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0003_response_concentrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
    ]
