# Generated by Django 2.2.4 on 2019-10-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191026_2055'),
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio_loudness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(default=0)),
                ('value', models.FloatField(default=0.0)),
                ('day_num', models.SmallIntegerField(default=0)),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Participant')),
            ],
        ),
    ]
