# Generated by Django 2.2.4 on 2019-10-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191027_0029'),
        ('sensor_data', '0002_audio_loudness'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acc',
            new_name='acc_sp',
        ),
        migrations.AddField(
            model_name='hrm',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='acc_sw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(default=0)),
                ('value_x', models.TextField(blank=True, default='')),
                ('value_y', models.TextField(blank=True, default='')),
                ('value_z', models.TextField(blank=True, default='')),
                ('device', models.CharField(default='', max_length=10)),
                ('ema_order', models.SmallIntegerField(default=0)),
                ('day_num', models.SmallIntegerField(default=0)),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Participant')),
            ],
        ),
    ]
