# Generated by Django 2.2.4 on 2019-10-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0003_auto_20191027_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc_sp',
            name='device',
        ),
        migrations.RemoveField(
            model_name='acc_sw',
            name='device',
        ),
    ]
