# Generated by Django 2.2.4 on 2019-10-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191028_2222'),
        ('sensor_data', '0004_auto_20191027_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_usage_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='DEFAULT_APP', max_length=128)),
                ('start_timestamp', models.BigIntegerField()),
                ('end_timestamp', models.BigIntegerField()),
                ('total_time_in_foreground', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Participant')),
            ],
            options={
                'unique_together': {('username', 'start_timestamp')},
            },
        ),
    ]
