# Generated by Django 2.2.4 on 2019-10-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0006_auto_20191028_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationary_dur',
            name='username',
        ),
        migrations.DeleteModel(
            name='app_usage',
        ),
        migrations.DeleteModel(
            name='stationary_dur',
        ),
    ]
