# Generated by Django 2.2.4 on 2019-10-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0007_auto_20191029_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_sp',
            name='value_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acc_sp',
            name='value_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acc_sp',
            name='value_z',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acc_sw',
            name='value_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acc_sw',
            name='value_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acc_sw',
            name='value_z',
            field=models.FloatField(default=0),
        ),
    ]
