# Generated by Django 2.2.4 on 2019-10-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0008_auto_20191029_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stddev_of_displacement',
            old_name='timestamp',
            new_name='timestamp_end',
        ),
        migrations.RenameField(
            model_name='stddev_of_displacement',
            old_name='confidence',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='stddev_of_displacement',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='stddev_of_displacement',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stddev_of_displacement',
            name='timestamp_start',
            field=models.BigIntegerField(default=0),
        ),
    ]
