# Generated by Django 2.2.4 on 2019-11-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0009_auto_20191030_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_sp',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='acc_sw',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='activities',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='app_usage_stats',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='audio_loudness',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='geofencing',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='gps_locations',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='hrm',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='light_intensity',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='max_dist_from_home',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='max_dist_two_locations',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='num_of_dif_places',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='phone_calls',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='radius_of_gyration',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='significant_motion',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='stddev_of_displacement',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='step_detector',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='total_dist_covered',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='unlocked_dur',
            name='lof_value',
            field=models.FloatField(default=-1),
        ),
    ]
