# Generated by Django 2.2.4 on 2019-11-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0010_auto_20191103_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_sp',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
