# Generated by Django 2.2.4 on 2019-12-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20191212_1654'),
        ('sensor_data', '0011_acc_sp_ema_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='stationary_dur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_start', models.BigIntegerField(default=0)),
                ('timestamp_end', models.BigIntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('day_num', models.SmallIntegerField(default=0)),
                ('lof_value', models.FloatField(default=-1)),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Participant')),
            ],
        ),
    ]
