# Generated by Django 2.2.4 on 2019-10-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=25)),
                ('phone_num', models.CharField(default='', max_length=16)),
                ('device_info', models.TextField(blank=True, default='')),
                ('password', models.CharField(max_length=16)),
                ('register_datetime', models.BigIntegerField(default=1572079437.826314)),
                ('last_login_datetime', models.BigIntegerField(default=1572079437.826314)),
                ('heartbeat_smartwatch', models.BigIntegerField(default=1572079437.826314)),
                ('heartbeat_smartphone', models.BigIntegerField(default=1572079437.826314)),
                ('daily_data_size_smartwatch', models.FloatField(default=0)),
                ('daily_data_size_smartphone', models.FloatField(default=0)),
                ('last_ds_smartphone', models.BigIntegerField(default=1572079437.826314)),
                ('last_ds_smartwatch', models.BigIntegerField(default=1572079437.826314)),
                ('type', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
